apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: db
  type: NodePort
  ports:  
  - name: http
    port: 30008
    targetPort: 5432
    nodePort: 30008
    protocol: TCP