apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: my-app
  type: NodePort
  ports:  
  - name: http
    port: 5431
    targetPort: 5431
    nodePort: 5431
    protocol: TCP
