apiVersion: v1
kind: Service
metadata:  
  name: my-lb-service
spec:
  selector:    
    app: webserver
  type: LoadBalancer
  ports:  
  - name: http
    port: 30008
    targetPort: 3000
    protocol: TCP