apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: service-db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5433
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-init-db
          mountPath: /docker-entrypoint-initdb.d
        - mountPath: /var/lib/postgresql/data
          name: db-persistent-storage
      volumes:
      - name: postgres-init-db
        configMap:
          name: postgres-init-config
  volumeClaimTemplates:
  - metadata:
      name: db-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi